window.opacity = 0.8
font.normal.family = "RobotoMono Nerd Font"
font.size = 12

[general]
import = ["~/.config/alacritty/themes/themes/dracula_plus.toml"]

[terminal]
shell.program = "/usr/bin/zsh"
shell.args = ["-c", "zellij"]
