import = ["~/.config/alacritty/themes/themes/rose-pine-dawn.toml"]
window.opacity = 0.8
font.normal.family = "RobotoMono Nerd Font"
font.size = 12
shell.program = "/usr/bin/zsh"
shell.args = ["-c", "zellij"]
