import = ["~/.config/alacritty/themes/themes/dracula_plus.toml"]
window.opacity = 0.8
font.normal.family = "RobotoMono Nerd Font"
font.size = 12

[shell]
shell.program = "zellij"
shell.args = ["-l", "portal"]
#shell.program = "/usr/bin/zsh"
#shell.args = ["-c", "zellij"]
